[versions]
activity = "1.12.0"
androidBaselineProfileMinSdk = "28"
androidCompileSdk = "36"
androidCore = "1.17.0"
androidGradlePlugin = "8.13.0"
androidJunit = "1.1.3"
androidMinSdk = "24"
androidTargetSdk = "36"
androidWearMinSdk = "25"
androidWearTargetSdk = "33"
appcompat = "1.7.1"
baselineprofile = "1.4.1"
benchmark = "1.4.1"
composeMultiplatformMaterial3 = "1.9.0"
composeMultiplatform = "1.10.0-beta01"
composeVectorize = "1.1.0"
dataStore = "1.1.7"
dependencyGraphGenerator = "0.8.0"
detekt = "1.23.8"
espressoCore = "3.4.0"
espressoCoreVersion = "3.7.0"
firebaseBom = "33.16.0"
firebaseCrashlytics = "3.0.6"
fonament = "0.0.1-alpha02"
glance = "1.1.1"
googleServices = "4.4.4"
jetbrainsNavigation = "2.9.1"
junit = "4.13.2"
junitVersion = "1.3.0"
koinBom = "4.1.1"
kotlin = "2.2.21"
kotlinCollectionsImmutable = "0.4.0"
kotlinCoroutines = "1.10.2"
kotlinDatetime = "0.7.1-0.6.x-compat"
kotlinSerializationJson = "1.9.0"
ksp = "2.3.2"
ktlint = "0.50.0"
lyricist = "1.7.0"
mockk = "1.14.6"
mockkCommon = "1.12.5"
navigationComposeExtended = "1.4.0"
ossLicenses = "0.10.9"
pigment = "0.6.0"
playServicesOssLicenses = "17.3.0"
playServicesWearable = "19.0.0"
profileinstaller = "1.4.1"
robolectric = "4.3.1"
splashscreen = "1.2.0"
spotless = "8.0.0"
sqlDelight = "2.1.0"
testCoreKtx = "1.4.0"
timber = "5.0.1"
uiautomator = "2.3.0"
wear = "1.3.0"
wearCompose = "1.5.5"
wearInput = "1.2.0"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "dataStore" }

androidx-glance-appWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }

androidx-wear-wear = { module = "androidx.wear:wear", version.ref = "wear" }
androidx-wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearCompose" }
androidx-wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }
androidx-wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }

dependencyGraphGenerator = { module = "com.vanniktech:gradle-dependency-graph-generator-plugin", version.ref = "dependencyGraphGenerator" }

detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

google-firebase-firebaseAnalyticsKtx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-firebaseCrashlyticsKtx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-playServicesOssLicenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
google-playServicesWearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }
google-ossLicensesPlugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicenses" }

jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrainsNavigation" }

jetbrains-compose-animationGraphics = { module = "org.jetbrains.compose.animation:animation-graphics", version.ref = "composeMultiplatform" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMultiplatformMaterial3" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
jetbrains-compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }

jetbrains-kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinCollectionsImmutable" }

jetbrains-kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
jetbrains-kotlin-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }
jetbrains-kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

jetbrains-kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }

jetbrains-kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

jetbrains-kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

junit = { module = "junit:junit", version.ref = "junit" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-androidXCompose = { module = "io.insert-koin:koin-androidx-compose" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }

lyricist-lyricist = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
lyricist-processor = { module = "cafe.adriel.lyricist:lyricist-processor", version.ref = "lyricist" }

mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }

sergiobelda-composeVectorize-core = { module = "dev.sergiobelda.compose.vectorize:compose-vectorize-core", version.ref = "composeVectorize" }
sergiobelda-fonament-diKoin = { module = "dev.sergiobelda.fonament:fonament-di-koin", version.ref = "fonament" }
sergiobelda-fonament-presentation = { module = "dev.sergiobelda.fonament:fonament-presentation", version.ref = "fonament" }
sergiobelda-navigationComposeExtended = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedAnnotation = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-annotation", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedCompiler = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-compiler", version.ref = "navigationComposeExtended" }
sergiobelda-navigationComposeExtendedWear = { module = "dev.sergiobelda.navigation.compose.extended:navigation-compose-extended-wear", version.ref = "navigationComposeExtended" }
sergiobelda-pigment = { module = "dev.sergiobelda.pigment:pigment", version.ref = "pigment" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

sqldelight-androidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-jvmDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-nativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-primitiveAdapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqlDelight" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
dependencyGraphGenerator = { id = "com.vanniktech.dependency.graph.generator", version.ref = "dependencyGraphGenerator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
jetbrains-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sergiobelda-composeVectorize = { id = "dev.sergiobelda.compose.vectorize", version.ref = "composeVectorize" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }

sergiobelda-gradle-base = { id = "dev.sergiobelda.gradle.base" }
sergiobelda-gradle-common-library-android = { id = "dev.sergiobelda.gradle.common.library.android" }
sergiobelda-gradle-common-ui = { id = "dev.sergiobelda.gradle.common.ui" }
sergiobelda-gradle-dependencyGraphGenerator = { id = "dev.sergiobelda.gradle.dependency-graph-generator" }
sergiobelda-gradle-detekt = { id = "dev.sergiobelda.gradle.detekt" }
sergiobelda-gradle-lint = { id = "dev.sergiobelda.gradle.lint" }
sergiobelda-gradle-spotless = { id = "dev.sergiobelda.gradle.spotless" }
