[versions]
activity = "1.8.2"
androidCompileSdk = "34"
androidCore = "1.12.0"
androidGradlePlugin = "8.3.1"
androidJunit = "1.1.3"
androidMinSdk = "24"
androidTargetSdk = "34"
androidWearMinSdk = "25"
androidWearTargetSdk = "33"
animationGraphicsAndroid = "1.6.5"
appcompat = "1.6.1"
composeCompiler = "1.5.11"
composeMultiplatform = "1.6.1"
composeVectorize = "0.7.0"
dataStore = "1.1.0-rc01"
dependencyGraphGenerator = "0.8.0"
espressoCore = "3.4.0"
firebaseBom = "32.8.0"
firebaseCrashlyticsGradle = "2.9.9"
glance = "1.0.0"
googleServices = "4.4.1"
junit = "4.13.2"
koinBom = "3.5.3"
kotlin = "1.9.23"
kotlinCoroutines = "1.8.0"
kotlinDatetime = "0.5.0"
kotlinSerializationJson = "1.6.3"
ksp = "1.9.23-1.0.19"
ktlint = "0.50.0"
lifecycle = "2.7.0"
lyricist = "1.6.2-1.8.20"
mockk = "1.13.10"
mockkCommon = "1.12.5"
navigation = "2.7.7"
ossLicenses = "0.10.6"
playServicesOssLicenses = "17.0.1"
playServicesWearable = "18.1.0"
robolectric = "4.3.1"
splashscreen = "1.1.0-rc01"
spotless = "6.25.0"
sqlDelight = "2.0.1"
testCoreKtx = "1.4.0"
timber = "5.0.1"
wear = "1.3.0"
wearCompose = "1.3.0"
wearInput = "1.2.0-alpha02"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-compose-animationGraphicsAndroid = { module = "androidx.compose.animation:animation-graphics-android", version.ref = "animationGraphicsAndroid" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidCore" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "dataStore" }

androidx-glance-appWidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }

androidx-lifecycle-runtimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-navigation-runtimeKtx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigation" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

composeVectorize-core = { module = "dev.sergiobelda.compose.vectorize:compose-vectorize-core", version.ref = "composeVectorize" }

dependencyGraphGenerator = { module = "com.vanniktech:gradle-dependency-graph-generator-plugin", version.ref = "dependencyGraphGenerator" }

google-firebase-firebaseAnalyticsKtx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-firebaseCrashlyticsKtx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

junit = { module = "junit:junit", version.ref = "junit" }

lyricist-lyricist = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
lyricist-processor = { module = "cafe.adriel.lyricist:lyricist-processor", version.ref = "lyricist" }

koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }

kotlin-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }
kotlin-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }

mockk-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockkCommon" }

google-playServicesOssLicenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServicesOssLicenses" }
google-playServicesWearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }
google-ossLicensesPlugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "ossLicenses" }

spotless-gradlePlugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

sqldelight-androidDriver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-jvmDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-nativeDriver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-primitiveAdapters = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

wear-wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "wearCompose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "wearCompose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "wearCompose" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wearInput" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeVectorize = { id = "dev.sergiobelda.compose.vectorize", version.ref = "composeVectorize" }
dependencyGraphGenerator = { id = "com.vanniktech.dependency.graph.generator", version.ref = "dependencyGraphGenerator" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradle" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
